import random

weird_facts_topics = [
    "Ongewone dierlijke vermogens",
    "Bizarre historische gebeurtenissen",
    "Vreemde voedselfeiten",
    "Vreemde medische aandoeningen",
    "Vreemde natuurverschijnselen",
    "Ongewone menselijke gedragingen",
    "Eigenaardige uitvindingen",
    "Vreemde culturele tradities",
    "Curieuze wereldrecords",
    "Mysterieuze verdwijningen",
    "Vreemde gewoonten van beroemdheden",
    "Ongewone planetaire feiten",
    "Bizarre archeologische ontdekkingen",
    "Vreemde toevalligheden",
    "Rare wetten over de hele wereld",
    "Onverklaarbare mysteries",
    "Vreemde stedelijke legendes",
    "Curieuze wetenschappelijke experimenten",
    "Ongewone paranormale verschijnselen",
    "Vreemde taalfeiten",
    "Ongewone hobby's",
    "Eigenaardige bijgeloven",
    "Bizarre modetrends",
    "Vreemde sporttradities",
    "Ongewone psychologische fenomenen",
    "Vreemde weersomstandigheden",
    "Ongewone lichaamsaanpassingen",
    "Nieuwsgierig diergedrag",
    "Bizarre kunstinstallaties",
    "Vreemde vervoersmethoden",
    "Eigenaardige architectonische ontwerpen",
    "Vreemde muziekinstrumenten",
    "Rare historische figuren",
    "Ongewone vakantiefeesten",
    "Nieuwsgierige technologische ontwikkelingen",
    "Vreemde plantenaanpassingen",
    "Bizarre beroemdheden endorsements",
    "Rare zakelijke praktijken",
    "Vreemde ontdekkingen in de oceaan",
    "Ongewone feiten over huisdieren",
    "Eigenaardige communicatiemethoden",
    "Bizarre schoonheidsnormen",
    "Vreemde werkgewoonten",
    "Rare culinaire delicatessen",
    "Vreemde fobieën",
    "Ongewone lichaamsfeiten",
    "Nieuwsgierige slaapstoornissen",
    "Bizarre medische behandelingen",
    "Vreemde dierlijke paringsrituelen",
    "Eigenaardige entertainmenttradities",
    "Rare mode-accessoires",
    "Vreemde dierenhybriden",
    "Ongebruikelijke sportregels",
    "Nieuwsgierige woordherkomsten",
    "Bizarre voertuigontwerpen",
    "Vreemde culturele taboes",
    "Eigenaardige eetgewoonten",
    "Rare beroemdheden diëten",
    "Vreemde reisbestemmingen",
    "Ongebruikelijke sportwedstrijden",
    "Nieuwsgierig insectengedrag",
    "Bizarre voedsel festivals",
    "Vreemde spookverhalen",
    "Eigenaardige muziekgenres",
    "Rare schoonheidswedstrijden",
    "Vreemde architectonische wonderen",
    "Ongebruikelijke angsten",
    "Nieuwsgierige sociale experimenten",
    "Bizarre feesttradities",
    "Vreemde babynamen",
    "Eigenaardige dierenfeiten",
    "Rare technologiegrappen",
    "Vreemde historische toevalligheden",
    "Ongebruikelijke stedelijke legendes",
    "Nieuwsgierige plantenaanpassingen",
    "Bizarre dierlijke paringsrituelen",
    "Vreemde beroemdheden fobieën",
    "Eigenaardige culinaire tradities",
    "Rare modetrends",
    "Vreemde sports tradities",
    "Ongebruikelijke medische praktijken",
    "Nieuwsgierige diercommunicatiemethoden",
    "Bizarre menselijke fobieën",
    "Vreemde natuurlijke rampen",
    "Eigenaardige lichaamsaanpassingen",
    "Rare psychologische stoornissen",
    "Vreemde stedelijke mythen",
    "Ongebruikelijke plantaardige aanpassingen",
    "Nieuwsgierige dierenhoaxes",
    "Bizarre medische experimenten",
    "Vreemde paranormale ontmoetingen",
    "Eigenaardige uitvindingen door de geschiedenis",
    "Rare sportmascottes",
    "Vreemde culturele taboes",
    "Eigenaardige communicatiemethoden",
    "Rare culturele praktijken",
    "Vreemde beroemdheden huisdieren",
    "Ongebruikelijke wetenschappelijke ontdekkingen",
    "Nieuwsgierige medische anomalieën",
    "Bizarre psychologische experimenten",
    "Vreemde religieuze rituelen",
    "Eigenaardige dierlijke aanpassingen",
    "Rare historische toevalligheden",
    "Vreemde architectonische fenomenen",
    "Ongebruikelijke modetrends",
    "Nieuwsgierige sportrituelen",
    "Bizarre culinaire delicatesse",
    "Vreemde kunstbewegingen",
    "Eigenaardige historische gebeurtenissen",
    "Rare taal dialecten",
    "Vreemde sport tradities",
    "Ongebruikelijke medische praktijken",
    "Nieuwsgierige dierenhoaxes",
    "Bizarre modetrends",
    "Vreemde stedelijke legendes",
    "Eigenaardige bijgeloven",
    "Rare paranormale ontmoetingen",
    "Vreemde culturele rituelen",
    "Ongebruikelijke natuurverschijnselen",
    "Nieuwsgierige historische artefacten",
    "Bizarre wetenschappelijke experimenten",
    "Vreemde gewoonten van beroemdheden",
    "Eigenaardige uitvindingen",
    "Rare diergedragingen",
    "Vreemde voedselcombinaties",
    "Ongebruikelijke mode-accessoires",
    "Nieuwsgierige medische aandoeningen",
    "Bizarre taalkundige verschijnselen",
]

def get_topic():
    random.shuffle(weird_facts_topics)
    return weird_facts_topics[0]